### PR TITLE
Try to get the recipe builder working

### PR DESCRIPTION
**Pull request by joelhaasnoot**
Hey Matt,
There are a *ton* of files missing from this repo. I've gone ahead and:
- found the JS dependencies online as best I could
- created inc.db.php based off the format in cloud control
- copied images from elsewhere to make it sort of look OK

Please, please, please check your local work and commit _all_ the files. Happy to help test and develop, but when code is left in a state like this, it's really hard!

Having said that, either I'm doing things wrong or the interface is buggy: the next and delete step buttons add steps at the top and don't seem to be in sync with the steps on the left so a little confused.

Joel

### CODE REVIEW

**Comment by margyle** [comment]
The steps at the top indicate the step has been added to the recipe, while the left is building the individual settings for each step. I will clarify that wording. I will jump on fixing the repo when I am working the weekly update, so could be tonight but might be tomorrow. Will definitely loop you in.

**Comment by mikekoetter** [comment]
Is this project still active/looking for developers?   Has the repo been updated as suggested?

**Comment by margyle** [comment]
Still active, although I have been focused on other parts of the project. I have a new completed OS build that should be pushed in the next couple of weeks.

**Comment by jjok** [comment]
I was holding off on doing anything until I've got the machine.

**Pull request closed without merging**
